/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	repackv1alpha1 "volcano.sh/apis/pkg/apis/repack/v1alpha1"
	applyconfigurationrepackv1alpha1 "volcano.sh/apis/pkg/client/applyconfiguration/repack/v1alpha1"
	scheme "volcano.sh/apis/pkg/client/clientset/versioned/scheme"
)

// RepackRunsGetter has a method to return a RepackRunInterface.
// A group's client should implement this interface.
type RepackRunsGetter interface {
	RepackRuns() RepackRunInterface
}

// RepackRunInterface has methods to work with RepackRun resources.
type RepackRunInterface interface {
	Create(ctx context.Context, repackRun *repackv1alpha1.RepackRun, opts v1.CreateOptions) (*repackv1alpha1.RepackRun, error)
	Update(ctx context.Context, repackRun *repackv1alpha1.RepackRun, opts v1.UpdateOptions) (*repackv1alpha1.RepackRun, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, repackRun *repackv1alpha1.RepackRun, opts v1.UpdateOptions) (*repackv1alpha1.RepackRun, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*repackv1alpha1.RepackRun, error)
	List(ctx context.Context, opts v1.ListOptions) (*repackv1alpha1.RepackRunList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *repackv1alpha1.RepackRun, err error)
	Apply(ctx context.Context, repackRun *applyconfigurationrepackv1alpha1.RepackRunApplyConfiguration, opts v1.ApplyOptions) (result *repackv1alpha1.RepackRun, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, repackRun *applyconfigurationrepackv1alpha1.RepackRunApplyConfiguration, opts v1.ApplyOptions) (result *repackv1alpha1.RepackRun, err error)
	RepackRunExpansion
}

// repackRuns implements RepackRunInterface
type repackRuns struct {
	*gentype.ClientWithListAndApply[*repackv1alpha1.RepackRun, *repackv1alpha1.RepackRunList, *applyconfigurationrepackv1alpha1.RepackRunApplyConfiguration]
}

// newRepackRuns returns a RepackRuns
func newRepackRuns(c *RepackV1alpha1Client) *repackRuns {
	return &repackRuns{
		gentype.NewClientWithListAndApply[*repackv1alpha1.RepackRun, *repackv1alpha1.RepackRunList, *applyconfigurationrepackv1alpha1.RepackRunApplyConfiguration](
			"repackruns",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *repackv1alpha1.RepackRun { return &repackv1alpha1.RepackRun{} },
			func() *repackv1alpha1.RepackRunList { return &repackv1alpha1.RepackRunList{} },
		),
	}
}
