/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	repackv1alpha1 "volcano.sh/apis/pkg/apis/repack/v1alpha1"
)

// RepackRunLister helps list RepackRuns.
// All objects returned here must be treated as read-only.
type RepackRunLister interface {
	// List lists all RepackRuns in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*repackv1alpha1.RepackRun, err error)
	// Get retrieves the RepackRun from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*repackv1alpha1.RepackRun, error)
	RepackRunListerExpansion
}

// repackRunLister implements the RepackRunLister interface.
type repackRunLister struct {
	listers.ResourceIndexer[*repackv1alpha1.RepackRun]
}

// NewRepackRunLister returns a new RepackRunLister.
func NewRepackRunLister(indexer cache.Indexer) RepackRunLister {
	return &repackRunLister{listers.New[*repackv1alpha1.RepackRun](indexer, repackv1alpha1.Resource("repackrun"))}
}
