//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisruptionHardFloors) DeepCopyInto(out *DisruptionHardFloors) {
	*out = *in
	if in.FreezePriorityAbove != nil {
		in, out := &in.FreezePriorityAbove, &out.FreezePriorityAbove
		*out = new(int32)
		**out = **in
	}
	if in.MaxMovesPerJob != nil {
		in, out := &in.MaxMovesPerJob, &out.MaxMovesPerJob
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisruptionHardFloors.
func (in *DisruptionHardFloors) DeepCopy() *DisruptionHardFloors {
	if in == nil {
		return nil
	}
	out := new(DisruptionHardFloors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisruptionPolicy) DeepCopyInto(out *DisruptionPolicy) {
	*out = *in
	if in.MinRunDuration != nil {
		in, out := &in.MinRunDuration, &out.MinRunDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxDisruptionScore != nil {
		in, out := &in.MaxDisruptionScore, &out.MaxDisruptionScore
		*out = new(int32)
		**out = **in
	}
	if in.RespectPDB != nil {
		in, out := &in.RespectPDB, &out.RespectPDB
		*out = new(bool)
		**out = **in
	}
	if in.Weights != nil {
		in, out := &in.Weights, &out.Weights
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HardFloors != nil {
		in, out := &in.HardFloors, &out.HardFloors
		*out = new(DisruptionHardFloors)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisruptionPolicy.
func (in *DisruptionPolicy) DeepCopy() *DisruptionPolicy {
	if in == nil {
		return nil
	}
	out := new(DisruptionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FragmentationTrigger) DeepCopyInto(out *FragmentationTrigger) {
	*out = *in
	if in.MinPendingPodGroups != nil {
		in, out := &in.MinPendingPodGroups, &out.MinPendingPodGroups
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FragmentationTrigger.
func (in *FragmentationTrigger) DeepCopy() *FragmentationTrigger {
	if in == nil {
		return nil
	}
	out := new(FragmentationTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaxPerRun) DeepCopyInto(out *MaxPerRun) {
	*out = *in
	if in.PodGroups != nil {
		in, out := &in.PodGroups, &out.PodGroups
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaxPerRun.
func (in *MaxPerRun) DeepCopy() *MaxPerRun {
	if in == nil {
		return nil
	}
	out := new(MaxPerRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingBlockedTrigger) DeepCopyInto(out *PendingBlockedTrigger) {
	*out = *in
	if in.MinPendingPodGroups != nil {
		in, out := &in.MinPendingPodGroups, &out.MinPendingPodGroups
		*out = new(int32)
		**out = **in
	}
	if in.MinBlockedDuration != nil {
		in, out := &in.MinBlockedDuration, &out.MinBlockedDuration
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingBlockedTrigger.
func (in *PendingBlockedTrigger) DeepCopy() *PendingBlockedTrigger {
	if in == nil {
		return nil
	}
	out := new(PendingBlockedTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMove) DeepCopyInto(out *PodMove) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMove.
func (in *PodMove) DeepCopy() *PodMove {
	if in == nil {
		return nil
	}
	out := new(PodMove)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodNomination) DeepCopyInto(out *PodNomination) {
	*out = *in
	if in.IdentityLabels != nil {
		in, out := &in.IdentityLabels, &out.IdentityLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExpirationTime != nil {
		in, out := &in.ExpirationTime, &out.ExpirationTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodNomination.
func (in *PodNomination) DeepCopy() *PodNomination {
	if in == nil {
		return nil
	}
	out := new(PodNomination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelievedPodGroup) DeepCopyInto(out *RelievedPodGroup) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelievedPodGroup.
func (in *RelievedPodGroup) DeepCopy() *RelievedPodGroup {
	if in == nil {
		return nil
	}
	out := new(RelievedPodGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackGoal) DeepCopyInto(out *RepackGoal) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackGoal.
func (in *RepackGoal) DeepCopy() *RepackGoal {
	if in == nil {
		return nil
	}
	out := new(RepackGoal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackMove) DeepCopyInto(out *RepackMove) {
	*out = *in
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(WorkloadRef)
		**out = **in
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = make([]PodMove, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackMove.
func (in *RepackMove) DeepCopy() *RepackMove {
	if in == nil {
		return nil
	}
	out := new(RepackMove)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackPlan) DeepCopyInto(out *RepackPlan) {
	*out = *in
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(RepackSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.Moves != nil {
		in, out := &in.Moves, &out.Moves
		*out = make([]RepackMove, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FreedNodes != nil {
		in, out := &in.FreedNodes, &out.FreedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Relief != nil {
		in, out := &in.Relief, &out.Relief
		*out = make([]RelievedPodGroup, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackPlan.
func (in *RepackPlan) DeepCopy() *RepackPlan {
	if in == nil {
		return nil
	}
	out := new(RepackPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackPolicy) DeepCopyInto(out *RepackPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackPolicy.
func (in *RepackPolicy) DeepCopy() *RepackPolicy {
	if in == nil {
		return nil
	}
	out := new(RepackPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepackPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackPolicyList) DeepCopyInto(out *RepackPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepackPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackPolicyList.
func (in *RepackPolicyList) DeepCopy() *RepackPolicyList {
	if in == nil {
		return nil
	}
	out := new(RepackPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepackPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackPolicySpec) DeepCopyInto(out *RepackPolicySpec) {
	*out = *in
	in.Trigger.DeepCopyInto(&out.Trigger)
	in.RunTemplate.DeepCopyInto(&out.RunTemplate)
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
	if in.SuccessfulRunsHistoryLimit != nil {
		in, out := &in.SuccessfulRunsHistoryLimit, &out.SuccessfulRunsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.FailedRunsHistoryLimit != nil {
		in, out := &in.FailedRunsHistoryLimit, &out.FailedRunsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackPolicySpec.
func (in *RepackPolicySpec) DeepCopy() *RepackPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RepackPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackPolicyStatus) DeepCopyInto(out *RepackPolicyStatus) {
	*out = *in
	if in.LastEvaluationTime != nil {
		in, out := &in.LastEvaluationTime, &out.LastEvaluationTime
		*out = (*in).DeepCopy()
	}
	if in.LastTriggerTime != nil {
		in, out := &in.LastTriggerTime, &out.LastTriggerTime
		*out = (*in).DeepCopy()
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = make([]corev1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackPolicyStatus.
func (in *RepackPolicyStatus) DeepCopy() *RepackPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RepackPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackRelief) DeepCopyInto(out *RepackRelief) {
	*out = *in
	if in.PodGroupRefs != nil {
		in, out := &in.PodGroupRefs, &out.PodGroupRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MinRelieved != nil {
		in, out := &in.MinRelieved, &out.MinRelieved
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackRelief.
func (in *RepackRelief) DeepCopy() *RepackRelief {
	if in == nil {
		return nil
	}
	out := new(RepackRelief)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackRun) DeepCopyInto(out *RepackRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackRun.
func (in *RepackRun) DeepCopy() *RepackRun {
	if in == nil {
		return nil
	}
	out := new(RepackRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepackRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackRunList) DeepCopyInto(out *RepackRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepackRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackRunList.
func (in *RepackRunList) DeepCopy() *RepackRunList {
	if in == nil {
		return nil
	}
	out := new(RepackRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepackRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackRunSpec) DeepCopyInto(out *RepackRunSpec) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(RepackScope)
		(*in).DeepCopyInto(*out)
	}
	if in.Relief != nil {
		in, out := &in.Relief, &out.Relief
		*out = new(RepackRelief)
		(*in).DeepCopyInto(*out)
	}
	if in.Goals != nil {
		in, out := &in.Goals, &out.Goals
		*out = make([]RepackGoal, len(*in))
		copy(*out, *in)
	}
	if in.DisruptionPolicy != nil {
		in, out := &in.DisruptionPolicy, &out.DisruptionPolicy
		*out = new(DisruptionPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxPerRun != nil {
		in, out := &in.MaxPerRun, &out.MaxPerRun
		*out = new(MaxPerRun)
		(*in).DeepCopyInto(*out)
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackRunSpec.
func (in *RepackRunSpec) DeepCopy() *RepackRunSpec {
	if in == nil {
		return nil
	}
	out := new(RepackRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackRunStatus) DeepCopyInto(out *RepackRunStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(RepackPlan)
		(*in).DeepCopyInto(*out)
	}
	if in.Nominations != nil {
		in, out := &in.Nominations, &out.Nominations
		*out = make([]PodNomination, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackRunStatus.
func (in *RepackRunStatus) DeepCopy() *RepackRunStatus {
	if in == nil {
		return nil
	}
	out := new(RepackRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackRunTemplateSpec) DeepCopyInto(out *RepackRunTemplateSpec) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackRunTemplateSpec.
func (in *RepackRunTemplateSpec) DeepCopy() *RepackRunTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(RepackRunTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackScope) DeepCopyInto(out *RepackScope) {
	*out = *in
	if in.PodGroups != nil {
		in, out := &in.PodGroups, &out.PodGroups
		*out = new(RepackSelectorTerm)
		(*in).DeepCopyInto(*out)
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = new(RepackSelectorTerm)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackScope.
func (in *RepackScope) DeepCopy() *RepackScope {
	if in == nil {
		return nil
	}
	out := new(RepackScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackSelector) DeepCopyInto(out *RepackSelector) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackSelector.
func (in *RepackSelector) DeepCopy() *RepackSelector {
	if in == nil {
		return nil
	}
	out := new(RepackSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackSelectorTerm) DeepCopyInto(out *RepackSelectorTerm) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = new(RepackSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = new(RepackSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackSelectorTerm.
func (in *RepackSelectorTerm) DeepCopy() *RepackSelectorTerm {
	if in == nil {
		return nil
	}
	out := new(RepackSelectorTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackSummary) DeepCopyInto(out *RepackSummary) {
	*out = *in
	if in.ResolvedScope != nil {
		in, out := &in.ResolvedScope, &out.ResolvedScope
		*out = new(ResolvedScope)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackSummary.
func (in *RepackSummary) DeepCopy() *RepackSummary {
	if in == nil {
		return nil
	}
	out := new(RepackSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepackTrigger) DeepCopyInto(out *RepackTrigger) {
	*out = *in
	if in.OnPendingBlocked != nil {
		in, out := &in.OnPendingBlocked, &out.OnPendingBlocked
		*out = new(PendingBlockedTrigger)
		(*in).DeepCopyInto(*out)
	}
	if in.OnFragmentation != nil {
		in, out := &in.OnFragmentation, &out.OnFragmentation
		*out = new(FragmentationTrigger)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepackTrigger.
func (in *RepackTrigger) DeepCopy() *RepackTrigger {
	if in == nil {
		return nil
	}
	out := new(RepackTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedScope) DeepCopyInto(out *ResolvedScope) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedScope.
func (in *ResolvedScope) DeepCopy() *ResolvedScope {
	if in == nil {
		return nil
	}
	out := new(ResolvedScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
