/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	repackv1alpha1 "volcano.sh/apis/pkg/apis/repack/v1alpha1"
)

// DisruptionPolicyApplyConfiguration represents a declarative configuration of the DisruptionPolicy type for use
// with apply.
//
// DisruptionPolicy (P1) tunes how running jobs may be disturbed. Lives on the
// Run (not in plugin config): plugin config only selects which scoring plugins
// are enabled. P0 ignores these and uses engine defaults.
type DisruptionPolicyApplyConfiguration struct {
	BundlePolicy *repackv1alpha1.BundlePolicy `json:"bundlePolicy,omitempty"`
	// MinRunDuration: jobs running less than this are not moved.
	MinRunDuration *v1.Duration `json:"minRunDuration,omitempty"`
	// MaxDisruptionScore is the disruption-cost red line.
	MaxDisruptionScore *int32 `json:"maxDisruptionScore,omitempty"`
	// RespectPDB enables PodDisruptionBudget compatibility.
	RespectPDB *bool `json:"respectPDB,omitempty"`
	// Lambda is the benefit-vs-friction trade-off as an integer weight (default 1).
	Lambda *int32 `json:"lambda,omitempty"`
	// Weights are per-disruption-term integer weights (relative; keys must match
	// scoring plugins enabled in config).
	Weights map[string]int32 `json:"weights,omitempty"`
	// HardFloors are optional hard guardrails (frozen anchors / per-job caps).
	HardFloors *DisruptionHardFloorsApplyConfiguration `json:"hardFloors,omitempty"`
}

// DisruptionPolicyApplyConfiguration constructs a declarative configuration of the DisruptionPolicy type for use with
// apply.
func DisruptionPolicy() *DisruptionPolicyApplyConfiguration {
	return &DisruptionPolicyApplyConfiguration{}
}

// WithBundlePolicy sets the BundlePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BundlePolicy field is set to the value of the last call.
func (b *DisruptionPolicyApplyConfiguration) WithBundlePolicy(value repackv1alpha1.BundlePolicy) *DisruptionPolicyApplyConfiguration {
	b.BundlePolicy = &value
	return b
}

// WithMinRunDuration sets the MinRunDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinRunDuration field is set to the value of the last call.
func (b *DisruptionPolicyApplyConfiguration) WithMinRunDuration(value v1.Duration) *DisruptionPolicyApplyConfiguration {
	b.MinRunDuration = &value
	return b
}

// WithMaxDisruptionScore sets the MaxDisruptionScore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxDisruptionScore field is set to the value of the last call.
func (b *DisruptionPolicyApplyConfiguration) WithMaxDisruptionScore(value int32) *DisruptionPolicyApplyConfiguration {
	b.MaxDisruptionScore = &value
	return b
}

// WithRespectPDB sets the RespectPDB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RespectPDB field is set to the value of the last call.
func (b *DisruptionPolicyApplyConfiguration) WithRespectPDB(value bool) *DisruptionPolicyApplyConfiguration {
	b.RespectPDB = &value
	return b
}

// WithLambda sets the Lambda field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lambda field is set to the value of the last call.
func (b *DisruptionPolicyApplyConfiguration) WithLambda(value int32) *DisruptionPolicyApplyConfiguration {
	b.Lambda = &value
	return b
}

// WithWeights puts the entries into the Weights field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Weights field,
// overwriting an existing map entries in Weights field with the same key.
func (b *DisruptionPolicyApplyConfiguration) WithWeights(entries map[string]int32) *DisruptionPolicyApplyConfiguration {
	if b.Weights == nil && len(entries) > 0 {
		b.Weights = make(map[string]int32, len(entries))
	}
	for k, v := range entries {
		b.Weights[k] = v
	}
	return b
}

// WithHardFloors sets the HardFloors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HardFloors field is set to the value of the last call.
func (b *DisruptionPolicyApplyConfiguration) WithHardFloors(value *DisruptionHardFloorsApplyConfiguration) *DisruptionPolicyApplyConfiguration {
	b.HardFloors = value
	return b
}
