/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DisruptionHardFloorsApplyConfiguration represents a declarative configuration of the DisruptionHardFloors type for use
// with apply.
//
// DisruptionHardFloors are optional hard guardrails.
type DisruptionHardFloorsApplyConfiguration struct {
	// FreezePriorityAbove: gangs with priority >= this never move.
	FreezePriorityAbove *int32 `json:"freezePriorityAbove,omitempty"`
	// MaxMovesPerJob caps relocations of any single PodGroup.
	MaxMovesPerJob *int32 `json:"maxMovesPerJob,omitempty"`
}

// DisruptionHardFloorsApplyConfiguration constructs a declarative configuration of the DisruptionHardFloors type for use with
// apply.
func DisruptionHardFloors() *DisruptionHardFloorsApplyConfiguration {
	return &DisruptionHardFloorsApplyConfiguration{}
}

// WithFreezePriorityAbove sets the FreezePriorityAbove field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FreezePriorityAbove field is set to the value of the last call.
func (b *DisruptionHardFloorsApplyConfiguration) WithFreezePriorityAbove(value int32) *DisruptionHardFloorsApplyConfiguration {
	b.FreezePriorityAbove = &value
	return b
}

// WithMaxMovesPerJob sets the MaxMovesPerJob field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxMovesPerJob field is set to the value of the last call.
func (b *DisruptionHardFloorsApplyConfiguration) WithMaxMovesPerJob(value int32) *DisruptionHardFloorsApplyConfiguration {
	b.MaxMovesPerJob = &value
	return b
}
