/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EvictionPolicyApplyConfiguration represents a declarative configuration of the EvictionPolicy type for use
// with apply.
//
// EvictionPolicy configures the execution behavior of Kubernetes Eviction API
// requests. Selection and scoring remain internal to the engine; this type owns
// only the mechanics of submitting an accepted move.
type EvictionPolicyApplyConfiguration struct {
	// GracePeriodSeconds overrides the graceful-termination period requested for
	// every Pod eviction in this Run. Unset preserves each Pod's
	// spec.terminationGracePeriodSeconds; 0 requests immediate termination.
	GracePeriodSeconds *int64 `json:"gracePeriodSeconds,omitempty"`
}

// EvictionPolicyApplyConfiguration constructs a declarative configuration of the EvictionPolicy type for use with
// apply.
func EvictionPolicy() *EvictionPolicyApplyConfiguration {
	return &EvictionPolicyApplyConfiguration{}
}

// WithGracePeriodSeconds sets the GracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GracePeriodSeconds field is set to the value of the last call.
func (b *EvictionPolicyApplyConfiguration) WithGracePeriodSeconds(value int64) *EvictionPolicyApplyConfiguration {
	b.GracePeriodSeconds = &value
	return b
}
