/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// MaxPerRunApplyConfiguration represents a declarative configuration of the MaxPerRun type for use
// with apply.
//
// MaxPerRun caps a single run's blast radius (distinct from K8s resource limits).
type MaxPerRunApplyConfiguration struct {
	// PodGroups caps distinct PodGroups moved (cross-resource count).
	PodGroups *int32 `json:"podGroups,omitempty"`
	// Resources caps accelerator cards moved per resource.
	Resources *v1.ResourceList `json:"resources,omitempty"`
}

// MaxPerRunApplyConfiguration constructs a declarative configuration of the MaxPerRun type for use with
// apply.
func MaxPerRun() *MaxPerRunApplyConfiguration {
	return &MaxPerRunApplyConfiguration{}
}

// WithPodGroups sets the PodGroups field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodGroups field is set to the value of the last call.
func (b *MaxPerRunApplyConfiguration) WithPodGroups(value int32) *MaxPerRunApplyConfiguration {
	b.PodGroups = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *MaxPerRunApplyConfiguration) WithResources(value v1.ResourceList) *MaxPerRunApplyConfiguration {
	b.Resources = &value
	return b
}
