/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PodMoveApplyConfiguration represents a declarative configuration of the PodMove type for use
// with apply.
//
// PodMove is one pod's planned relocation (pure plan; DryRun/Execute identical).
type PodMoveApplyConfiguration struct {
	// Name is the pod name (a plan-time snapshot for random-named controllers).
	Name *string `json:"name,omitempty"`
	// FromNode is where the pod currently runs.
	FromNode *string `json:"fromNode,omitempty"`
	// ToNode is the pod's PLANNED target node (soft nomination, no reservation).
	ToNode *string `json:"toNode,omitempty"`
	// Cards is the accelerator cards (GPU/NPU) this pod occupies.
	Cards *int64 `json:"cards,omitempty"`
}

// PodMoveApplyConfiguration constructs a declarative configuration of the PodMove type for use with
// apply.
func PodMove() *PodMoveApplyConfiguration {
	return &PodMoveApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PodMoveApplyConfiguration) WithName(value string) *PodMoveApplyConfiguration {
	b.Name = &value
	return b
}

// WithFromNode sets the FromNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FromNode field is set to the value of the last call.
func (b *PodMoveApplyConfiguration) WithFromNode(value string) *PodMoveApplyConfiguration {
	b.FromNode = &value
	return b
}

// WithToNode sets the ToNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ToNode field is set to the value of the last call.
func (b *PodMoveApplyConfiguration) WithToNode(value string) *PodMoveApplyConfiguration {
	b.ToNode = &value
	return b
}

// WithCards sets the Cards field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cards field is set to the value of the last call.
func (b *PodMoveApplyConfiguration) WithCards(value int64) *PodMoveApplyConfiguration {
	b.Cards = &value
	return b
}
