/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	repackv1alpha1 "volcano.sh/apis/pkg/apis/repack/v1alpha1"
)

// PodNominationApplyConfiguration represents a declarative configuration of the PodNomination type for use
// with apply.
//
// PodNomination records one relocated pod's replacement placement
// (Execute-only). The placement controller patches pod.status.nominatedNodeName, claiming
// the replacement per the placement matching contract (proposal §5.2.2):
// victimPodName exact match in the active PodGroup -> schedulingRequirementsHash
// equality -> homogeneous PodGroup fallback.
type PodNominationApplyConfiguration struct {
	// Namespace of the target pod (PodGroup shares this namespace).
	Namespace *string `json:"namespace,omitempty"`
	// PodGroupName the pod belongs to.
	PodGroupName *string `json:"podGroupName,omitempty"`
	// ReplacementPodGroupName is the latest PodGroup generation that recreates
	// this nomination's replacement Pod. It remains empty when the workload reuses
	// the original PodGroup name. The placement controller owns this runtime field
	// and may advance it after another full-group recreation; PodGroupName remains
	// the immutable plan-time identity for audit.
	ReplacementPodGroupName *string `json:"replacementPodGroupName,omitempty"`
	// VictimPodName is the evicted pod's name: audit + exact fast-path when the
	// controller recreates the replacement with the same name.
	VictimPodName *string `json:"victimPodName,omitempty"`
	// SchedulingRequirementsHash is an opaque hash of normalized scheduling
	// requirements from the victim Pod. It is populated only when the PodGroup
	// defines SubGroup policies and is compared only for equality when matching a
	// renamed replacement Pod. Empty means the PodGroup is treated as homogeneous.
	SchedulingRequirementsHash *string `json:"schedulingRequirementsHash,omitempty"`
	// NodeName is the immutable plan-time target node. It is retained for audit even
	// if a later placement reconciliation selects another receiver.
	NodeName *string `json:"nodeName,omitempty"`
	// SelectedNodeName is the current receiver selected from the live scheduler
	// snapshot. It is written before the placement gate is removed.
	SelectedNodeName *string `json:"selectedNodeName,omitempty"`
	// ReplacementPodName and ReplacementPodUID identify the concrete Pod held by
	// the placement gate. They are controller-owned status fields.
	ReplacementPodName *string    `json:"replacementPodName,omitempty"`
	ReplacementPodUID  *types.UID `json:"replacementPodUID,omitempty"`
	// ActualNodeName is populated after the replacement is bound. It makes drift
	// visible without overwriting the plan-time or selected target.
	ActualNodeName *string `json:"actualNodeName,omitempty"`
	// ExpirationTime bounds re-assertion; after it the nomination is Expired.
	ExpirationTime *v1.Time `json:"expirationTime,omitempty"`
	// Phase is the controller-owned placement lifecycle.
	Phase *repackv1alpha1.PodNominationPhase `json:"phase,omitempty"`
}

// PodNominationApplyConfiguration constructs a declarative configuration of the PodNomination type for use with
// apply.
func PodNomination() *PodNominationApplyConfiguration {
	return &PodNominationApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithNamespace(value string) *PodNominationApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithPodGroupName sets the PodGroupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodGroupName field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithPodGroupName(value string) *PodNominationApplyConfiguration {
	b.PodGroupName = &value
	return b
}

// WithReplacementPodGroupName sets the ReplacementPodGroupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplacementPodGroupName field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithReplacementPodGroupName(value string) *PodNominationApplyConfiguration {
	b.ReplacementPodGroupName = &value
	return b
}

// WithVictimPodName sets the VictimPodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VictimPodName field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithVictimPodName(value string) *PodNominationApplyConfiguration {
	b.VictimPodName = &value
	return b
}

// WithSchedulingRequirementsHash sets the SchedulingRequirementsHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingRequirementsHash field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithSchedulingRequirementsHash(value string) *PodNominationApplyConfiguration {
	b.SchedulingRequirementsHash = &value
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithNodeName(value string) *PodNominationApplyConfiguration {
	b.NodeName = &value
	return b
}

// WithSelectedNodeName sets the SelectedNodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SelectedNodeName field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithSelectedNodeName(value string) *PodNominationApplyConfiguration {
	b.SelectedNodeName = &value
	return b
}

// WithReplacementPodName sets the ReplacementPodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplacementPodName field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithReplacementPodName(value string) *PodNominationApplyConfiguration {
	b.ReplacementPodName = &value
	return b
}

// WithReplacementPodUID sets the ReplacementPodUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplacementPodUID field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithReplacementPodUID(value types.UID) *PodNominationApplyConfiguration {
	b.ReplacementPodUID = &value
	return b
}

// WithActualNodeName sets the ActualNodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActualNodeName field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithActualNodeName(value string) *PodNominationApplyConfiguration {
	b.ActualNodeName = &value
	return b
}

// WithExpirationTime sets the ExpirationTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpirationTime field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithExpirationTime(value v1.Time) *PodNominationApplyConfiguration {
	b.ExpirationTime = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithPhase(value repackv1alpha1.PodNominationPhase) *PodNominationApplyConfiguration {
	b.Phase = &value
	return b
}
