/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PodNominationApplyConfiguration represents a declarative configuration of the PodNomination type for use
// with apply.
//
// PodNomination steers one relocated pod's replacement onto a target node
// (Execute-only). The reconciler patches pod.status.nominatedNodeName, claiming
// the replacement per the landing-identity contract (proposal §5.2.2):
// victimPodName exact match -> identityLabels (label match) -> fungible (any
// pending pod in the PodGroup).
type PodNominationApplyConfiguration struct {
	// Namespace of the target pod (PodGroup shares this namespace).
	Namespace *string `json:"namespace,omitempty"`
	// PodGroupName the pod belongs to.
	PodGroupName *string `json:"podGroupName,omitempty"`
	// VictimPodName is the evicted pod's name: audit + exact fast-path when the
	// controller recreates the replacement with the same name.
	VictimPodName *string `json:"victimPodName,omitempty"`
	// IdentityLabels are the labels that identify the replacement pod across
	// reconstruction (key = the identity label the contract used, e.g.
	// repack.volcano.sh/pod-identity, or a native-kind label such as
	// apps.kubernetes.io/pod-index; value = its value). The reconciler claims a
	// pending pod whose labels are a superset. Empty = fungible (any pod in the
	// PodGroup). Self-describing: which label + value is visible in status.
	IdentityLabels map[string]string `json:"identityLabels,omitempty"`
	// NodeName is the target node to nominate the replacement onto.
	NodeName *string `json:"nodeName,omitempty"`
	// ExpirationTime bounds re-assertion; after it the nomination is Expired.
	ExpirationTime *v1.Time `json:"expirationTime,omitempty"`
	// Phase: Pending (not yet matched) / Bound (patched onto a replacement) /
	// Expired (elapsed without a match).
	Phase *string `json:"phase,omitempty"`
}

// PodNominationApplyConfiguration constructs a declarative configuration of the PodNomination type for use with
// apply.
func PodNomination() *PodNominationApplyConfiguration {
	return &PodNominationApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithNamespace(value string) *PodNominationApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithPodGroupName sets the PodGroupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodGroupName field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithPodGroupName(value string) *PodNominationApplyConfiguration {
	b.PodGroupName = &value
	return b
}

// WithVictimPodName sets the VictimPodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VictimPodName field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithVictimPodName(value string) *PodNominationApplyConfiguration {
	b.VictimPodName = &value
	return b
}

// WithIdentityLabels puts the entries into the IdentityLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the IdentityLabels field,
// overwriting an existing map entries in IdentityLabels field with the same key.
func (b *PodNominationApplyConfiguration) WithIdentityLabels(entries map[string]string) *PodNominationApplyConfiguration {
	if b.IdentityLabels == nil && len(entries) > 0 {
		b.IdentityLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.IdentityLabels[k] = v
	}
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithNodeName(value string) *PodNominationApplyConfiguration {
	b.NodeName = &value
	return b
}

// WithExpirationTime sets the ExpirationTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpirationTime field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithExpirationTime(value v1.Time) *PodNominationApplyConfiguration {
	b.ExpirationTime = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *PodNominationApplyConfiguration) WithPhase(value string) *PodNominationApplyConfiguration {
	b.Phase = &value
	return b
}
