/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	repackv1alpha1 "volcano.sh/apis/pkg/apis/repack/v1alpha1"
)

// PodPlacementStatusApplyConfiguration represents a declarative configuration of the PodPlacementStatus type for use
// with apply.
//
// PodPlacementStatus contains the replacement Pod identity, selected receiver,
// observed binding, and placement deadline.
type PodPlacementStatusApplyConfiguration struct {
	// Phase is the current replacement placement lifecycle phase.
	Phase *repackv1alpha1.PodPlacementPhase `json:"phase,omitempty"`
	// SelectedNodeName is the receiver selected from the live scheduler snapshot.
	// It is written before the placement gate is removed.
	SelectedNodeName *string `json:"selectedNodeName,omitempty"`
	// ReplacementPodName and ReplacementPodUID identify the concrete replacement
	// Pod held by the placement gate.
	ReplacementPodName *string    `json:"replacementPodName,omitempty"`
	ReplacementPodUID  *types.UID `json:"replacementPodUID,omitempty"`
	// ActualNodeName is populated after the replacement is bound. Comparing it
	// with SelectedNodeName reveals an alternative scheduler placement.
	ActualNodeName *string `json:"actualNodeName,omitempty"`
	// ExpirationTime bounds placement reconciliation.
	ExpirationTime *v1.Time `json:"expirationTime,omitempty"`
}

// PodPlacementStatusApplyConfiguration constructs a declarative configuration of the PodPlacementStatus type for use with
// apply.
func PodPlacementStatus() *PodPlacementStatusApplyConfiguration {
	return &PodPlacementStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *PodPlacementStatusApplyConfiguration) WithPhase(value repackv1alpha1.PodPlacementPhase) *PodPlacementStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithSelectedNodeName sets the SelectedNodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SelectedNodeName field is set to the value of the last call.
func (b *PodPlacementStatusApplyConfiguration) WithSelectedNodeName(value string) *PodPlacementStatusApplyConfiguration {
	b.SelectedNodeName = &value
	return b
}

// WithReplacementPodName sets the ReplacementPodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplacementPodName field is set to the value of the last call.
func (b *PodPlacementStatusApplyConfiguration) WithReplacementPodName(value string) *PodPlacementStatusApplyConfiguration {
	b.ReplacementPodName = &value
	return b
}

// WithReplacementPodUID sets the ReplacementPodUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplacementPodUID field is set to the value of the last call.
func (b *PodPlacementStatusApplyConfiguration) WithReplacementPodUID(value types.UID) *PodPlacementStatusApplyConfiguration {
	b.ReplacementPodUID = &value
	return b
}

// WithActualNodeName sets the ActualNodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActualNodeName field is set to the value of the last call.
func (b *PodPlacementStatusApplyConfiguration) WithActualNodeName(value string) *PodPlacementStatusApplyConfiguration {
	b.ActualNodeName = &value
	return b
}

// WithExpirationTime sets the ExpirationTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpirationTime field is set to the value of the last call.
func (b *PodPlacementStatusApplyConfiguration) WithExpirationTime(value v1.Time) *PodPlacementStatusApplyConfiguration {
	b.ExpirationTime = &value
	return b
}
