/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// PodRelocationStatusApplyConfiguration represents a declarative configuration of the PodRelocationStatus type for use
// with apply.
//
// PodRelocationStatus records the immutable plan identity and the independently
// reconciled eviction and replacement placement state for one relocated Pod.
type PodRelocationStatusApplyConfiguration struct {
	// Namespace of the target pod (PodGroup shares this namespace).
	Namespace *string `json:"namespace,omitempty"`
	// PodGroupName the pod belongs to.
	PodGroupName *string `json:"podGroupName,omitempty"`
	// ReplacementPodGroupName is the latest PodGroup generation that recreates
	// this relocation's replacement Pod. It remains empty when the workload reuses
	// the original PodGroup name. The placement controller owns this runtime field
	// and may advance it after another full-group recreation; PodGroupName remains
	// the immutable plan-time identity for audit.
	ReplacementPodGroupName *string `json:"replacementPodGroupName,omitempty"`
	// VictimPodName is the evicted pod's name: audit + exact fast-path when the
	// controller recreates the replacement with the same name.
	VictimPodName *string `json:"victimPodName,omitempty"`
	// VictimPodUID identifies the exact Pod instance selected by the plan. The
	// engine uses it as an eviction precondition and during crash recovery so a
	// same-name replacement is never evicted by a replayed request.
	VictimPodUID *types.UID `json:"victimPodUID,omitempty"`
	// SchedulingRequirementsHash is an opaque hash of normalized scheduling
	// requirements from the victim Pod. It is populated only when the PodGroup
	// defines SubGroup policies and is compared only for equality when matching a
	// renamed replacement Pod. Empty means the PodGroup is treated as homogeneous.
	SchedulingRequirementsHash *string `json:"schedulingRequirementsHash,omitempty"`
	// PlannedNodeName is the immutable plan-time target node. It is retained for
	// audit even if a later placement reconciliation selects another receiver.
	PlannedNodeName *string `json:"plannedNodeName,omitempty"`
	// Eviction is the engine-owned durable victim eviction state.
	Eviction *PodEvictionStatusApplyConfiguration `json:"eviction,omitempty"`
	// Placement is the controller-owned replacement placement state.
	Placement *PodPlacementStatusApplyConfiguration `json:"placement,omitempty"`
}

// PodRelocationStatusApplyConfiguration constructs a declarative configuration of the PodRelocationStatus type for use with
// apply.
func PodRelocationStatus() *PodRelocationStatusApplyConfiguration {
	return &PodRelocationStatusApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *PodRelocationStatusApplyConfiguration) WithNamespace(value string) *PodRelocationStatusApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithPodGroupName sets the PodGroupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodGroupName field is set to the value of the last call.
func (b *PodRelocationStatusApplyConfiguration) WithPodGroupName(value string) *PodRelocationStatusApplyConfiguration {
	b.PodGroupName = &value
	return b
}

// WithReplacementPodGroupName sets the ReplacementPodGroupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReplacementPodGroupName field is set to the value of the last call.
func (b *PodRelocationStatusApplyConfiguration) WithReplacementPodGroupName(value string) *PodRelocationStatusApplyConfiguration {
	b.ReplacementPodGroupName = &value
	return b
}

// WithVictimPodName sets the VictimPodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VictimPodName field is set to the value of the last call.
func (b *PodRelocationStatusApplyConfiguration) WithVictimPodName(value string) *PodRelocationStatusApplyConfiguration {
	b.VictimPodName = &value
	return b
}

// WithVictimPodUID sets the VictimPodUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VictimPodUID field is set to the value of the last call.
func (b *PodRelocationStatusApplyConfiguration) WithVictimPodUID(value types.UID) *PodRelocationStatusApplyConfiguration {
	b.VictimPodUID = &value
	return b
}

// WithSchedulingRequirementsHash sets the SchedulingRequirementsHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingRequirementsHash field is set to the value of the last call.
func (b *PodRelocationStatusApplyConfiguration) WithSchedulingRequirementsHash(value string) *PodRelocationStatusApplyConfiguration {
	b.SchedulingRequirementsHash = &value
	return b
}

// WithPlannedNodeName sets the PlannedNodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PlannedNodeName field is set to the value of the last call.
func (b *PodRelocationStatusApplyConfiguration) WithPlannedNodeName(value string) *PodRelocationStatusApplyConfiguration {
	b.PlannedNodeName = &value
	return b
}

// WithEviction sets the Eviction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Eviction field is set to the value of the last call.
func (b *PodRelocationStatusApplyConfiguration) WithEviction(value *PodEvictionStatusApplyConfiguration) *PodRelocationStatusApplyConfiguration {
	b.Eviction = value
	return b
}

// WithPlacement sets the Placement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Placement field is set to the value of the last call.
func (b *PodRelocationStatusApplyConfiguration) WithPlacement(value *PodPlacementStatusApplyConfiguration) *PodRelocationStatusApplyConfiguration {
	b.Placement = value
	return b
}
