/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RepackScopeApplyConfiguration represents a declarative configuration of the RepackScope type for use
// with apply.
//
// RepackScope bounds the run on two independent axes: which PodGroups may move
// and which nodes participate. Each axis has symmetric include/exclude
// (label selector and/or explicit name list); exclude wins.
//
// Everything is a PodGroup: selection is expressed uniformly against PodGroups
// (the engine's action/cost unit is the gang), so both `selector` (PG labels)
// and `names` (PG "namespace/name") address the SAME object. This works for
// every workload type — Volcano-native (vcjob), K8s-native (Deployment /
// StatefulSet / ...), and user-custom CRDs — because Volcano's pg-controller
// inherits pod template labels onto the auto-created PodGroup (system/controller
// labels such as pod-template-hash are filtered out), so a PG label selector
// addresses all of them. Note `names` is only practical for deterministically
// named PodGroups (e.g. vcjob); auto-created PGs have UID-derived names, so those
// are selected via `selector`.
type RepackScopeApplyConfiguration struct {
	PodGroups *RepackSelectorTermApplyConfiguration `json:"podGroups,omitempty"`
	Nodes     *RepackSelectorTermApplyConfiguration `json:"nodes,omitempty"`
}

// RepackScopeApplyConfiguration constructs a declarative configuration of the RepackScope type for use with
// apply.
func RepackScope() *RepackScopeApplyConfiguration {
	return &RepackScopeApplyConfiguration{}
}

// WithPodGroups sets the PodGroups field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodGroups field is set to the value of the last call.
func (b *RepackScopeApplyConfiguration) WithPodGroups(value *RepackSelectorTermApplyConfiguration) *RepackScopeApplyConfiguration {
	b.PodGroups = value
	return b
}

// WithNodes sets the Nodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Nodes field is set to the value of the last call.
func (b *RepackScopeApplyConfiguration) WithNodes(value *RepackSelectorTermApplyConfiguration) *RepackScopeApplyConfiguration {
	b.Nodes = value
	return b
}
