/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RepackResultApplyConfiguration represents a declarative configuration of the RepackResult type for use
// with apply.
//
// RepackResult is the Execute-only observed outcome. Plan remains the immutable
// audit record; Result reports what was accepted and what the cluster looked like
// after replacement placement completed.
type RepackResultApplyConfiguration struct {
	// FragAfterPercent is the observed cluster-wide fragmentation after Execute.
	// When MetricsVerified is false, it conservatively equals plan.fragBeforePercent.
	FragAfterPercent *int32 `json:"fragAfterPercent,omitempty"`
	// FreedNodeCount is the number of plan.freedNodes actually free of the target
	// resource in the verified terminal snapshot.
	FreedNodeCount *int32 `json:"freedNodeCount,omitempty"`
	// FreedNodes are the plan.freedNodes verified free of the target resource in
	// the terminal scheduler snapshot. The list is sorted for deterministic
	// status and lets operators compare the realized node set with plan.freedNodes.
	FreedNodes []string `json:"freedNodes,omitempty"`
	// MovedCardCount is the accelerator-card total for accepted Pod evictions.
	MovedCardCount *int64 `json:"movedCardCount,omitempty"`
	// MetricsVerified reports whether FragAfterPercent, FreedNodeCount, and
	// FreedNodes came from a coherent scheduler snapshot after replacement binding.
	MetricsVerified *bool `json:"metricsVerified,omitempty"`
}

// RepackResultApplyConfiguration constructs a declarative configuration of the RepackResult type for use with
// apply.
func RepackResult() *RepackResultApplyConfiguration {
	return &RepackResultApplyConfiguration{}
}

// WithFragAfterPercent sets the FragAfterPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FragAfterPercent field is set to the value of the last call.
func (b *RepackResultApplyConfiguration) WithFragAfterPercent(value int32) *RepackResultApplyConfiguration {
	b.FragAfterPercent = &value
	return b
}

// WithFreedNodeCount sets the FreedNodeCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FreedNodeCount field is set to the value of the last call.
func (b *RepackResultApplyConfiguration) WithFreedNodeCount(value int32) *RepackResultApplyConfiguration {
	b.FreedNodeCount = &value
	return b
}

// WithFreedNodes adds the given value to the FreedNodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FreedNodes field.
func (b *RepackResultApplyConfiguration) WithFreedNodes(values ...string) *RepackResultApplyConfiguration {
	for i := range values {
		b.FreedNodes = append(b.FreedNodes, values[i])
	}
	return b
}

// WithMovedCardCount sets the MovedCardCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MovedCardCount field is set to the value of the last call.
func (b *RepackResultApplyConfiguration) WithMovedCardCount(value int64) *RepackResultApplyConfiguration {
	b.MovedCardCount = &value
	return b
}

// WithMetricsVerified sets the MetricsVerified field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetricsVerified field is set to the value of the last call.
func (b *RepackResultApplyConfiguration) WithMetricsVerified(value bool) *RepackResultApplyConfiguration {
	b.MetricsVerified = &value
	return b
}
