/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	repackv1alpha1 "volcano.sh/apis/pkg/apis/repack/v1alpha1"
)

// RepackRunSpecApplyConfiguration represents a declarative configuration of the RepackRunSpec type for use
// with apply.
//
// ---------- spec ----------
// RepackRunSpec is the user-facing, self-contained spec of one repack job.
// P0 is self-contained (hand-written in full); relief and disruptionPolicy are
// P1 — fields are reserved here so the schema is stable, but the engine
// honors engine defaults in P0.
//
// Admission is enforced entirely at the apiserver via CEL/markers (no controller
// admission step): mode is an enum, goals is capped at one entry, and the spec is
// immutable. Scope is optional in both modes: an omitted scope means whole-cluster
// (all PodGroups, all nodes); how much a run actually relocates is bounded by the
// engine's internal plan (maxPerRun, cooldown, K=1, PDB), not by requiring a scope.
type RepackRunSpecApplyConfiguration struct {
	// Mode selects DryRun (simulate + report) or Execute (act).
	Mode *repackv1alpha1.RepackMode `json:"mode,omitempty"`
	// Scope bounds which PodGroups may move and which nodes participate.
	Scope *RepackScopeApplyConfiguration `json:"scope,omitempty"`
	// Relief (P1): pending PodGroups this run aims to make schedulable.
	Relief *RepackReliefApplyConfiguration `json:"relief,omitempty"`
	// Goals is the per-resource fragmentation target. P0/P1: exactly one entry
	// (a run defragments a single accelerator resource); multi-resource is P2+.
	Goals []RepackGoalApplyConfiguration `json:"goals,omitempty"`
	// DisruptionPolicy (P1): how/whether running jobs may be disturbed.
	DisruptionPolicy *DisruptionPolicyApplyConfiguration `json:"disruptionPolicy,omitempty"`
	// MaxPerRun caps the blast radius of a single run.
	MaxPerRun *MaxPerRunApplyConfiguration `json:"maxPerRun,omitempty"`
	// TTLSecondsAfterFinished: auto-DELETE this Run that long after it finishes
	// (like Job). Unset = not auto-deleted (P0; Policy default is P1).
	TTLSecondsAfterFinished *int64 `json:"ttlSecondsAfterFinished,omitempty"`
}

// RepackRunSpecApplyConfiguration constructs a declarative configuration of the RepackRunSpec type for use with
// apply.
func RepackRunSpec() *RepackRunSpecApplyConfiguration {
	return &RepackRunSpecApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *RepackRunSpecApplyConfiguration) WithMode(value repackv1alpha1.RepackMode) *RepackRunSpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *RepackRunSpecApplyConfiguration) WithScope(value *RepackScopeApplyConfiguration) *RepackRunSpecApplyConfiguration {
	b.Scope = value
	return b
}

// WithRelief sets the Relief field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Relief field is set to the value of the last call.
func (b *RepackRunSpecApplyConfiguration) WithRelief(value *RepackReliefApplyConfiguration) *RepackRunSpecApplyConfiguration {
	b.Relief = value
	return b
}

// WithGoals adds the given value to the Goals field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Goals field.
func (b *RepackRunSpecApplyConfiguration) WithGoals(values ...*RepackGoalApplyConfiguration) *RepackRunSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithGoals")
		}
		b.Goals = append(b.Goals, *values[i])
	}
	return b
}

// WithDisruptionPolicy sets the DisruptionPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisruptionPolicy field is set to the value of the last call.
func (b *RepackRunSpecApplyConfiguration) WithDisruptionPolicy(value *DisruptionPolicyApplyConfiguration) *RepackRunSpecApplyConfiguration {
	b.DisruptionPolicy = value
	return b
}

// WithMaxPerRun sets the MaxPerRun field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPerRun field is set to the value of the last call.
func (b *RepackRunSpecApplyConfiguration) WithMaxPerRun(value *MaxPerRunApplyConfiguration) *RepackRunSpecApplyConfiguration {
	b.MaxPerRun = value
	return b
}

// WithTTLSecondsAfterFinished sets the TTLSecondsAfterFinished field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLSecondsAfterFinished field is set to the value of the last call.
func (b *RepackRunSpecApplyConfiguration) WithTTLSecondsAfterFinished(value int64) *RepackRunSpecApplyConfiguration {
	b.TTLSecondsAfterFinished = &value
	return b
}
