/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
	repackv1alpha1 "volcano.sh/apis/pkg/apis/repack/v1alpha1"
)

// RepackRunStatusApplyConfiguration represents a declarative configuration of the RepackRunStatus type for use
// with apply.
//
// ---------- status ----------
// RepackRunStatus reports lifecycle and business output. Conditions are
// authoritative; phase is derived. "Worth repacking?" is folded into the
// terminal Complete condition's reason (RepackRecommended / Executed /
// NoFragmentation / BelowGoalThreshold), not a summary field.
type RepackRunStatusApplyConfiguration struct {
	// Phase is a derived projection of conditions.
	Phase *repackv1alpha1.RepackPhase `json:"phase,omitempty"`
	// Conditions are the authoritative facts (Job-style: Queued/
	// Progressing/Complete/Failed/Cancelled). Admission is CEL-only, so there is
	// no Admitted condition. The Complete condition's reason also encodes whether
	// repacking was worthwhile.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// Message is a one-line human summary written at terminal state.
	Message *string `json:"message,omitempty"`
	// StartTime is when the run first entered Running.
	StartTime *metav1.Time `json:"startTime,omitempty"`
	// CompletionTime is when the run first reached a terminal phase (TTL anchor).
	CompletionTime *metav1.Time `json:"completionTime,omitempty"`
	// Plan is the immutable plan-time decision in both modes. DryRun reports what
	// would be done; Execute preserves the complete pre-eviction plan so rejected
	// or degraded actions remain auditable. Actual Execute metrics live in Result.
	Plan *RepackPlanApplyConfiguration `json:"plan,omitempty"`
	// Result is the Execute-only observed outcome. It is absent for DryRun and
	// when Execute failed before any eviction was attempted.
	Result *RepackResultApplyConfiguration `json:"result,omitempty"`
	// Nominations are the durable placement-steering intents produced by Execute:
	// one entry per relocated pod, consumed by the nomination reconciler per the
	// placement identity contract (victimPodName exact match -> identityLabels ->
	// fungible). See the design proposal §5.2.2.
	Nominations []PodNominationApplyConfiguration `json:"nominations,omitempty"`
}

// RepackRunStatusApplyConfiguration constructs a declarative configuration of the RepackRunStatus type for use with
// apply.
func RepackRunStatus() *RepackRunStatusApplyConfiguration {
	return &RepackRunStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *RepackRunStatusApplyConfiguration) WithPhase(value repackv1alpha1.RepackPhase) *RepackRunStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RepackRunStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *RepackRunStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *RepackRunStatusApplyConfiguration) WithMessage(value string) *RepackRunStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *RepackRunStatusApplyConfiguration) WithStartTime(value metav1.Time) *RepackRunStatusApplyConfiguration {
	b.StartTime = &value
	return b
}

// WithCompletionTime sets the CompletionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletionTime field is set to the value of the last call.
func (b *RepackRunStatusApplyConfiguration) WithCompletionTime(value metav1.Time) *RepackRunStatusApplyConfiguration {
	b.CompletionTime = &value
	return b
}

// WithPlan sets the Plan field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Plan field is set to the value of the last call.
func (b *RepackRunStatusApplyConfiguration) WithPlan(value *RepackPlanApplyConfiguration) *RepackRunStatusApplyConfiguration {
	b.Plan = value
	return b
}

// WithResult sets the Result field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Result field is set to the value of the last call.
func (b *RepackRunStatusApplyConfiguration) WithResult(value *RepackResultApplyConfiguration) *RepackRunStatusApplyConfiguration {
	b.Result = value
	return b
}

// WithNominations adds the given value to the Nominations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Nominations field.
func (b *RepackRunStatusApplyConfiguration) WithNominations(values ...*PodNominationApplyConfiguration) *RepackRunStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNominations")
		}
		b.Nominations = append(b.Nominations, *values[i])
	}
	return b
}
