/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RepackSelectorTermApplyConfiguration represents a declarative configuration of the RepackSelectorTerm type for use
// with apply.
//
// RepackSelectorTerm is an include/exclude pair (exclude wins).
type RepackSelectorTermApplyConfiguration struct {
	Include *RepackSelectorApplyConfiguration `json:"include,omitempty"`
	Exclude *RepackSelectorApplyConfiguration `json:"exclude,omitempty"`
}

// RepackSelectorTermApplyConfiguration constructs a declarative configuration of the RepackSelectorTerm type for use with
// apply.
func RepackSelectorTerm() *RepackSelectorTermApplyConfiguration {
	return &RepackSelectorTermApplyConfiguration{}
}

// WithInclude sets the Include field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Include field is set to the value of the last call.
func (b *RepackSelectorTermApplyConfiguration) WithInclude(value *RepackSelectorApplyConfiguration) *RepackSelectorTermApplyConfiguration {
	b.Include = value
	return b
}

// WithExclude sets the Exclude field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exclude field is set to the value of the last call.
func (b *RepackSelectorTermApplyConfiguration) WithExclude(value *RepackSelectorApplyConfiguration) *RepackSelectorTermApplyConfiguration {
	b.Exclude = value
	return b
}
