/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RepackMoveApplyConfiguration represents a declarative configuration of the RepackMove type for use
// with apply.
//
// RepackMove is one PodGroup's relocation. fromNode/toNode are per-pod (a gang's
// pods may be spread across nodes / move to multiple targets), so they live in
// pods[]; the PodGroup level keeps identity + aggregate.
type RepackMoveApplyConfiguration struct {
	// Namespace of this PodGroup (owner and pods share it).
	Namespace *string `json:"namespace,omitempty"`
	// PodGroupName is the precise scheduling-dimension identity (matches scope).
	PodGroupName *string `json:"podGroupName,omitempty"`
	// Owner is the user-facing workload owning this PodGroup (PodGroup is an
	// internal object). Taken from the PG controller ownerReference (not walked
	// up); empty for ownerless bare pods.
	Owner *WorkloadRefApplyConfiguration `json:"owner,omitempty"`
	// Cards is this PodGroup's total accelerator cards moved (= sum of pods[].cards).
	Cards *int64 `json:"cards,omitempty"`
	// Pods is the per-pod relocation detail (only relocated pods appear).
	Pods []PodMoveApplyConfiguration `json:"pods,omitempty"`
}

// RepackMoveApplyConfiguration constructs a declarative configuration of the RepackMove type for use with
// apply.
func RepackMove() *RepackMoveApplyConfiguration {
	return &RepackMoveApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *RepackMoveApplyConfiguration) WithNamespace(value string) *RepackMoveApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithPodGroupName sets the PodGroupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodGroupName field is set to the value of the last call.
func (b *RepackMoveApplyConfiguration) WithPodGroupName(value string) *RepackMoveApplyConfiguration {
	b.PodGroupName = &value
	return b
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *RepackMoveApplyConfiguration) WithOwner(value *WorkloadRefApplyConfiguration) *RepackMoveApplyConfiguration {
	b.Owner = value
	return b
}

// WithCards sets the Cards field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cards field is set to the value of the last call.
func (b *RepackMoveApplyConfiguration) WithCards(value int64) *RepackMoveApplyConfiguration {
	b.Cards = &value
	return b
}

// WithPods adds the given value to the Pods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Pods field.
func (b *RepackMoveApplyConfiguration) WithPods(values ...*PodMoveApplyConfiguration) *RepackMoveApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPods")
		}
		b.Pods = append(b.Pods, *values[i])
	}
	return b
}
