/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RepackReliefApplyConfiguration represents a declarative configuration of the RepackRelief type for use
// with apply.
//
// RepackRelief (reserved) names pending PodGroups to unblock (beneficiaries; they
// themselves are not moved).
type RepackReliefApplyConfiguration struct {
	// PodGroupRefs are "namespace/name" of pending PodGroups to relieve.
	PodGroupRefs []string `json:"podGroupRefs,omitempty"`
	// MinRelieved: at least this many must become schedulable to be worthwhile.
	MinRelieved *int32 `json:"minRelieved,omitempty"`
}

// RepackReliefApplyConfiguration constructs a declarative configuration of the RepackRelief type for use with
// apply.
func RepackRelief() *RepackReliefApplyConfiguration {
	return &RepackReliefApplyConfiguration{}
}

// WithPodGroupRefs adds the given value to the PodGroupRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PodGroupRefs field.
func (b *RepackReliefApplyConfiguration) WithPodGroupRefs(values ...string) *RepackReliefApplyConfiguration {
	for i := range values {
		b.PodGroupRefs = append(b.PodGroupRefs, values[i])
	}
	return b
}

// WithMinRelieved sets the MinRelieved field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinRelieved field is set to the value of the last call.
func (b *RepackReliefApplyConfiguration) WithMinRelieved(value int32) *RepackReliefApplyConfiguration {
	b.MinRelieved = &value
	return b
}
