/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RepackPlanApplyConfiguration represents a declarative configuration of the RepackPlan type for use
// with apply.
//
// RepackPlan is the terminal output, populated in BOTH modes with the same
// shape: DryRun = predicted plan; Execute = executed plan. Three progressive
// layers (summary + moves + freedNodes), capped by maxItems. Schema evolves with
// the CRD apiVersion (no internal formatVersion).
type RepackPlanApplyConfiguration struct {
	// Summary is the flat, at-a-glance layer (UI lists / alerts / printers read this).
	Summary *RepackSummaryApplyConfiguration `json:"summary,omitempty"`
	// Moves is the per-PodGroup relocation detail; fromNode/toNode live per-pod
	// inside pods[]. moves is a pure plan (identical in DryRun and Execute).
	Moves []RepackMoveApplyConfiguration `json:"moves,omitempty"`
	// FreedNodes are the names of nodes the plan empties.
	FreedNodes []string `json:"freedNodes,omitempty"`
}

// RepackPlanApplyConfiguration constructs a declarative configuration of the RepackPlan type for use with
// apply.
func RepackPlan() *RepackPlanApplyConfiguration {
	return &RepackPlanApplyConfiguration{}
}

// WithSummary sets the Summary field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Summary field is set to the value of the last call.
func (b *RepackPlanApplyConfiguration) WithSummary(value *RepackSummaryApplyConfiguration) *RepackPlanApplyConfiguration {
	b.Summary = value
	return b
}

// WithMoves adds the given value to the Moves field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Moves field.
func (b *RepackPlanApplyConfiguration) WithMoves(values ...*RepackMoveApplyConfiguration) *RepackPlanApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMoves")
		}
		b.Moves = append(b.Moves, *values[i])
	}
	return b
}

// WithFreedNodes adds the given value to the FreedNodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FreedNodes field.
func (b *RepackPlanApplyConfiguration) WithFreedNodes(values ...string) *RepackPlanApplyConfiguration {
	for i := range values {
		b.FreedNodes = append(b.FreedNodes, values[i])
	}
	return b
}
