/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RepackSelectorApplyConfiguration represents a declarative configuration of the RepackSelector type for use
// with apply.
//
// RepackSelector matches by label selector and/or explicit names (union).
type RepackSelectorApplyConfiguration struct {
	Selector *v1.LabelSelectorApplyConfiguration `json:"selector,omitempty"`
	// Names are "namespace/name" for PodGroups, or node names for nodes.
	Names []string `json:"names,omitempty"`
}

// RepackSelectorApplyConfiguration constructs a declarative configuration of the RepackSelector type for use with
// apply.
func RepackSelector() *RepackSelectorApplyConfiguration {
	return &RepackSelectorApplyConfiguration{}
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *RepackSelectorApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *RepackSelectorApplyConfiguration {
	b.Selector = value
	return b
}

// WithNames adds the given value to the Names field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Names field.
func (b *RepackSelectorApplyConfiguration) WithNames(values ...string) *RepackSelectorApplyConfiguration {
	for i := range values {
		b.Names = append(b.Names, values[i])
	}
	return b
}
