/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// RepackGoalApplyConfiguration represents a declarative configuration of the RepackGoal type for use
// with apply.
//
// RepackGoal is one resource's fragmentation target.
type RepackGoalApplyConfiguration struct {
	// Resource is the accelerator to defragment (e.g. nvidia.com/gpu). Only
	// fully-qualified extended resources (a name containing "/") are supported;
	// core compute resources such as cpu, memory, ephemeral-storage and pods are
	// rejected, because repack only consolidates scalar accelerator capacity.
	Resource *v1.ResourceName `json:"resource,omitempty"`
	// MinFragImprovementPercent is the required minimum drop in this resource's
	// fragmentation, in percentage points (0-100). 0 = any benefit counts.
	MinFragImprovementPercent *int32 `json:"minFragImprovementPercent,omitempty"`
}

// RepackGoalApplyConfiguration constructs a declarative configuration of the RepackGoal type for use with
// apply.
func RepackGoal() *RepackGoalApplyConfiguration {
	return &RepackGoalApplyConfiguration{}
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *RepackGoalApplyConfiguration) WithResource(value v1.ResourceName) *RepackGoalApplyConfiguration {
	b.Resource = &value
	return b
}

// WithMinFragImprovementPercent sets the MinFragImprovementPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinFragImprovementPercent field is set to the value of the last call.
func (b *RepackGoalApplyConfiguration) WithMinFragImprovementPercent(value int32) *RepackGoalApplyConfiguration {
	b.MinFragImprovementPercent = &value
	return b
}
