/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RepackSummaryApplyConfiguration represents a declarative configuration of the RepackSummary type for use
// with apply.
//
// RepackSummary is the flat second layer of the plan. Single-resource per run
// (goals maxItems=1): the fragmentation figures are for that one accelerator
// resource (goals[0].resource) — no per-resource breakdown. Multi-resource is
// P2+ (would add a per-resource layer then).
type RepackSummaryApplyConfiguration struct {
	// Fragmentation before/after for the run's resource, in percentage points
	// (0-100). Improvement = before - after (derive client-side).
	FragBeforePercent *int32 `json:"fragBeforePercent,omitempty"`
	FragAfterPercent  *int32 `json:"fragAfterPercent,omitempty"`
	// FreedNodeCount is the number of nodes freed (headline; printer column).
	FreedNodeCount *int32 `json:"freedNodeCount,omitempty"`
	// MovedCardCount is the total accelerator cards relocated (the run's resource).
	MovedCardCount *int64                           `json:"movedCardCount,omitempty"`
	ResolvedScope  *ResolvedScopeApplyConfiguration `json:"resolvedScope,omitempty"`
}

// RepackSummaryApplyConfiguration constructs a declarative configuration of the RepackSummary type for use with
// apply.
func RepackSummary() *RepackSummaryApplyConfiguration {
	return &RepackSummaryApplyConfiguration{}
}

// WithFragBeforePercent sets the FragBeforePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FragBeforePercent field is set to the value of the last call.
func (b *RepackSummaryApplyConfiguration) WithFragBeforePercent(value int32) *RepackSummaryApplyConfiguration {
	b.FragBeforePercent = &value
	return b
}

// WithFragAfterPercent sets the FragAfterPercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FragAfterPercent field is set to the value of the last call.
func (b *RepackSummaryApplyConfiguration) WithFragAfterPercent(value int32) *RepackSummaryApplyConfiguration {
	b.FragAfterPercent = &value
	return b
}

// WithFreedNodeCount sets the FreedNodeCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FreedNodeCount field is set to the value of the last call.
func (b *RepackSummaryApplyConfiguration) WithFreedNodeCount(value int32) *RepackSummaryApplyConfiguration {
	b.FreedNodeCount = &value
	return b
}

// WithMovedCardCount sets the MovedCardCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MovedCardCount field is set to the value of the last call.
func (b *RepackSummaryApplyConfiguration) WithMovedCardCount(value int64) *RepackSummaryApplyConfiguration {
	b.MovedCardCount = &value
	return b
}

// WithResolvedScope sets the ResolvedScope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResolvedScope field is set to the value of the last call.
func (b *RepackSummaryApplyConfiguration) WithResolvedScope(value *ResolvedScopeApplyConfiguration) *RepackSummaryApplyConfiguration {
	b.ResolvedScope = value
	return b
}
